name: "MLOps Project"

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://backend:8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./backend/models:/app/models
    ports:
      - "8000:8000"
    restart: unless-stopped

  mlflow:
    image: ubuntu/mlflow:2.1.1_1.0-22.04
    container_name: mlflow
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - ./mlflow_data:/mlflow
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
