name: "segmentation"

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://backend:8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend/models:/app/models
    ports:
      - "8000:8000"
    restart: unless-stopped
