name: Build and Push to Registry
on: [push]
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy the model
        run: |
          docker compose build frontend backend
          docker tag frontend ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}-frontend:${{ github.sha }}
          docker tag backend ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}-backend:${{ github.sha }}
        
      - name: Login to the registry
        run: docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}
        
      - name: Push to the registry
        run: |
          docker push ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}-frontend:${{ github.sha }}
          docker push ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}-backend:${{ github.sha }}
          

      - name: Setup SSH with PEM file
        run: |
          echo "${{ secrets.VM_PEM_FILE }}" | base64 --decode > /tmp/private-key.pem
          chmod 600 /tmp/private-key.pem

      - name: Pull on the VM
        run: |
          ssh -i /tmp/private-key.pem -o StrictHostKeyChecking=no ${{ secrets.REGISTRY_USER }}@${{ secrets.IP }} << EOF
            docker pull ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}-frontend:${{ github.sha }}
            docker pull ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}-backend:${{ github.sha }}
          
            docker stop frontend backend || true && docker rm frontend backend || true

            docker run -d -p 8501:8501 --name frontend ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}-frontend:${{ github.sha }}
            docker run -d -p 8000:8000 --name backend ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}-backend:${{ github.sha }}
          EOF
